# Quizz!

## Easy

In [2]:
import torch

In [3]:
torch.ones(10) * 2

tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [4]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
torch.arange(10)[-1] #--> 9

tensor(9)

In [6]:
torch.arange(10)[2:] #[2...]

tensor([2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
torch.arange(10)[:-2]

tensor([0, 1, 2, 3, 4, 5, 6, 7])

## Medium

In [8]:
torch.cat((torch.zeros(10), torch.ones(10)))

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.])

In [9]:
# print(torch.zeros((10,3)))
# print(torch.ones((10, 2)))

torch.cat((torch.zeros((10,3)), torch.ones((10, 2))), dim=-1) #在最后一个dim上拼接

tensor([[0., 0., 0., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 1., 1.]])

## Hard

In [11]:
print(torch.arange(10)[..., None]) #在切片操作中，None 的意思是“在这里插入一个大小为 1 的新维度”。
print(torch.arange(10))

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [12]:
torch.abs(torch.arange(10)[..., None] - torch.arange(10))

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 0, 1, 2, 3, 4, 5, 6, 7, 8],
        [2, 1, 0, 1, 2, 3, 4, 5, 6, 7],
        [3, 2, 1, 0, 1, 2, 3, 4, 5, 6],
        [4, 3, 2, 1, 0, 1, 2, 3, 4, 5],
        [5, 4, 3, 2, 1, 0, 1, 2, 3, 4],
        [6, 5, 4, 3, 2, 1, 0, 1, 2, 3],
        [7, 6, 5, 4, 3, 2, 1, 0, 1, 2],
        [8, 7, 6, 5, 4, 3, 2, 1, 0, 1],
        [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]])

In [13]:
torch.arange(10)[:, None] == torch.arange(10)

tensor([[ True, False, False, False, False, False, False, False, False, False],
        [False,  True, False, False, False, False, False, False, False, False],
        [False, False,  True, False, False, False, False, False, False, False],
        [False, False, False,  True, False, False, False, False, False, False],
        [False, False, False, False,  True, False, False, False, False, False],
        [False, False, False, False, False,  True, False, False, False, False],
        [False, False, False, False, False, False,  True, False, False, False],
        [False, False, False, False, False, False, False,  True, False, False],
        [False, False, False, False, False, False, False, False,  True, False],
        [False, False, False, False, False, False, False, False, False,  True]])